logging:
    file:
        name: /logs/sboard.log
    level:
        jdbc:
            resultsettable: info
            sqlonly: info
            sqltiming: info
        org:
            hibernate:
                orm:
                    jdbc:
                        bind: trace
                sql: debug
        root: info
app:
    version: 0.0.2
server:
    port: 8082
    servlet:
        context-path: /sboard
spring:
    application:
        name: sboard
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 1234
        url: jdbc:mysql://localhost:3306/jboard
        username: jboard
    devtools:
        livereload:
            enabled: true
    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
                show_sql: true
    mail:
        host: smtp.gmail.com
            port: 465
            username: repos8646@gmail.com
            password: zkviewfzptghjpez # google 앱 비밀번호
            properties:
                mail:
                    smtp:
                        auth: true
                        timeout: 5000
                        starttls:
                            enable: true
